import { ANTIGRAVITY_BASE_AGENT, type AgentDefinition } from "./types";

export const createStarterAgentDefinition = (id = "agent-lab-data-analyst"): AgentDefinition => ({
  id,
  description: "Data analyst agent generated by the managed agent lab.",
  base_agent: ANTIGRAVITY_BASE_AGENT,
  system_instruction:
    "You are a careful data analyst. Prefer reproducible scripts, include concise findings, and save useful artifacts in /workspace/output.",
  tools: [
    { type: "code_execution" },
    { type: "google_search" },
    { type: "url_context" }
  ],
  base_environment: {
    type: "remote",
    sources: [
      {
        type: "inline",
        target: ".agents/AGENTS.md",
        content:
          "Always explain assumptions before analysis. Save generated files under /workspace/output."
      },
      {
        type: "inline",
        target: ".agents/skills/report-writer/SKILL.md",
        content:
          "---\nname: report-writer\ndescription: Create concise analysis reports\n---\n# Report Writer\n\nWhen asked for analysis, produce a short executive summary, a reproducible method, and a list of output files."
      }
    ]
  }
});

